---
- name: "setup ntp.conf"
  template:
    src: ntp.conf.default.j2
    dest: "{{ ntp_file_conf }}"
    backup: "{{ ntp_backup }}"
    owner: root
    group: root
    mode: 0640
  notify:
    - restart ntp
