---
# tasks file for ntp

- name: Add the OS specific varibles
  include_vars: "os-{{ ansible_os_family }}.yml"
  tags:
    - ntp
    - ntp:setup
    - ntp:service
    - ntp:config

# Debian(setup) specific tasks
- include: setup-Debian.yml
  when: "ansible_os_family == 'Debian'"
  tags:
    - ntp
    - ntp:setup

# RedHat(setup) specific tasks
- include: setup-RedHat.yml
  when: "ansible_os_family == 'RedHat'"
  tags:
    - ntp
    - ntp:setup

# Suse(setup) specific tasks
- include: setup-Suse.yml
  when: "ansible_os_family == 'Suse'"
  tags:
    - ntp
    - ntp:setup

# Common configuration tasks tasks
- include: config.yml
  tags:
    - ntp
    - ntp:config

# Common service tasks
- include: service.yml
  tags:
    - ntp
    - ntp:service
