---
# tasks file for ntp

- name: Add the OS specific varibles
  include_vars: "os-{{ ansible_os_family }}.yml"
  tags:
    - ntp
    - ntp:setup
    - ntp:service
    - ntp:config

# Debian(setup) specific tasks
- name: include setup tasks
  include: setup-{{ ansible_os_family }}.yml
  tags:
    - ntp
    - ntp:setup

# Common configuration tasks tasks
- name: include config tasks
  include: config.yml
  tags:
    - ntp
    - ntp:config

# Common service tasks
- name: include service tasks
  include: service.yml
  tags:
    - ntp
    - ntp:service
